<a href="https://colab.research.google.com/github/MasonWang025/ai-club-materials/blob/main/pytorch-intro/pytorch_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

#Tensors
Tensor describe an n-dimensional array (can be numbers, vectors, matrices, etc.).

All elements in the tensor have the same data type.

Dimensions are accessed by any tensor's `.shape` property.

In [2]:
# basic tensors
# number
t1 = torch.tensor(4.)
print("number:", t1, t1.dtype, t1.shape)

# vectors
t2 = torch.tensor([1., 2, 3, 4]) # all elements have same dtype
print("list:", t2, t2.dtype, t2.shape)

# matrix
t3 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10]])
print("matrix:", t3.shape)

# 3-dimensional
t4 = torch.tensor([
                   [[1, 1, 1], 
                    [1, 1, 1],
                    [1, 1, 1],
                    [1, 1, 1]],
                   [[2, 2, 2], 
                    [2, 2, 2],
                    [2, 2, 2],
                    [2, 2, 2]]
                   ])
print("3d array:", t4.shape)


number: tensor(4.) torch.float32 torch.Size([])
list: tensor([1., 2., 3., 4.]) torch.float32 torch.Size([4])
matrix: torch.Size([3, 2])
3d array: torch.Size([2, 4, 3])


#Tensor Operations and Gradients

In [3]:
# basic tensor operation
# creating tensors
x = torch.tensor(69.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(9., requires_grad=True)
print(x, w, b)
# arithmetic operations
y = w * x + b
print(y)

tensor(69.) tensor(4., requires_grad=True) tensor(9., requires_grad=True)
tensor(285., grad_fn=<AddBackward0>)


In [4]:
# compute derivatives
y.backward()
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(69.)
dy/db: tensor(1.)


#Interoperability with Numpy
Mathematical and scientific computing in Python (efficient operations on large arrays). Many important supporting libaries (Matplotlib, OpenCV, Pandas).

In [5]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
print(x)

y = torch.from_numpy(x)
print(y)
print(x.dtype, y.dtype)

z = y.numpy()
print(z)

[[1. 2.]
 [3. 4.]]
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
float64 torch.float64
[[1. 2.]
 [3. 4.]]
